name: Test CDK Infrastructure

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test_cdk_infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"

      - name: Test Items CDK stack
        run: |
          npm install -g aws-cdk
          npm install
          cd lambda
          cd items
          ls
          pwd

      - name: Echo Success
        run: |
          npm run test
          echo "Testing successful"
