name: Test CDK Infrastructure

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test_cdk_infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.16.1"

      - name: Test Items CDK stack
        run: |
          npm install -g aws-cdk
          npm install
          npm run test

      - name: Echo Success
        run: |
          echo "Testing successful"
